package constants

const (
	MISSING_LOGIN_INPUT                   = "Thiếu thông tin đăng nhập"
	SUCCESS_LOGIN                         = "Đăng nhập thành công"
	ERROR_INTERNAL_ERROR                  = "Lỗi nội bộ máy chủ"
	INVALID_USERNAME                      = "Username không tìm thấy"
	INVALID_EMAIL                         = "Email không tìm thấy"
	ERROR_CREATE                          = "Không thể thêm mới dữ liệu này"
	ERROR_EDIT                            = "Chỉnh sửa thất bại"
	INVALID_PASSWORD                      = "Mật khẩu không đúng"
	ACCOUNT_NOT_ACTIVE                    = "Tài khoản không được phép hoạt động"
	NOT_ADMIN                             = "Chỉ admin được dùng dữ liệu này"
	NOT_MANAGER                           = "Chỉ quản lý được dùng dữ liệu này"
	NOT_MODARATOR                         = "Chỉ nhân viên kiểm duyệt nội dung được dùng dữ liệu này"
	NOT_SELLER                            = "Chỉ nhân viên bán vé được dùng dữ liệu này"
	ERROR_INPUT                           = "Thiếu dữ liệu input yêu cầu"
	ERROR_PARSE_DATA_TO_LOCALS            = "Dữ liệu truyền vào không đúng yêu cầu"
	ERROR_DATA_IS_ALSO                    = "Lỗi dữ liệu đồng thời tồn tại"
	DATA_INPUT_IS_NOT_NUMBER              = "Dữ liệu truyền vào phải là số"
	DATA_INPUT_IS_NOT_BOOL                = "Dữ liệu truyền vào phải là boolean"
	NEW_PASSWORD_NOT_SAME_REPEAT_PASSWORD = "Mật khẩu mới và mật khẩu nhắc lại không trùng khớp"
	NEW_PASSWORD_SAME_CURRENT_PASSWORD    = "Mật khẩu mới không được trùng với mật khẩu hiện tại"
	CAN_NOT_HASH_PASSWORD                 = "Không thể mã hoá được mật khẩu"
	NOT_FOUND_RECORDS                     = "Không tìm thấy dữ liệu"
	ROLE_NOT_EXISTS                       = "Chức vụ không tồn tại trên hệ thống"
	IDENTIFICATION_CARD_EXISTS            = "Số CCCD này đã được đăng kí"
	PHONE_NUMBER_CUSTOMER_EXISTS          = "Số điện thoại khách hàng đã tồn tại"
	EMAIL_CUSTOMER_EXISTS                 = "Tài khoản email khách hàng đã tồn tại"
	CAN_NOT_EDIT_CINEMA                   = "Bạn không có quyền chỉnh sửa dữ liệu này"
	CAN_NOT_GET_CINEMA                    = "Bạn không có quyền xem dữ liệu này"
	CAN_NOT_EDIT_SEAT                     = "Bạn không có quyền chỉnh ghế ngồi "
	STATUS_CINEMA_CANCEL                  = "Tình trạng rạp chiếu đang bảo trì"
	STATUS_ROOM_CANCEL                    = "Tình trạng phòng chiếu đang bảo trì"
	ACCOUNT_NOT_PERMISSION                = "Bạn không có quyền xem dữ liệu này"
	ERROR_UPDATE                          = " Lỗi không thể cập nhật"
	ERROR_CREATE_ADDRESS                  = "Lỗi không tạo được địa chỉ mới"
)

var ROLE = []string{"ADMIN", "MANAGER", "MODERATOR", "SELL"}
var ROLE_ADMIN = "ADMIN"
var ROLE_MANAGER = "MANAGER"
var ROLE_MODERATOR = "MODERATOR"
var ROLE_STAFF = "STAFF"

var STATUS_TICKET = []string{"BOOKED", "CONFIRMED", "EXPIRED"}
var TICKET_BOOKED = "BOOKED"
var TICKET_CONFIRM = "CONFIRMED"
var TICKET_EXPIRED = "EXPRIEDs"
